### ISSUE TITLE
Update the base JDBC driver to 42 

### ISSUE THREAD

**Issue by kskim80** [bitnine-oss/agensgraph-jdbc#9]
https://jdbc.postgresql.org/documentation/changelog.html#version_42.0.0

**Comment by mlogue** [comment]
The JDBC major version number of the PG has been changed.
Therefore, backward compatibility is not guaranteed.
> PostgreSQL JDBC Driver 42.0.0 Released!
> Notable changes
> * Support for PostgreSQL versions below 8.2 was dropped
> * java.util.logging is now used for logging: logging documentation

To use PG JDBC 42.0.0, it is better to change the AgensGraph JDBC version to 2.0.0.
When I change the dependency to 42.0.0, a compiler error occurs because the Logger class has been removed.
